### ISSUE TITLE
Not an issue, more like a warning: i-Buddy was starting to burn

### ISSUE THREAD

**Issue by megfault** [armijnhemel/py3buddy#4]
Hi Armijn,

lacking a more suitable way to contact you, I just want to let you know that during a simple test at the NixCon hackday the i-Buddy started to smoke and we quickly disconnected it.

So, we will probably finish nix-packaging it, but I want to save other developers from getting their computer catch fire. I might add a very big warning to the top of the README. Just wanted to inform you and other devs ASAP to prevent accidents before we finish our work here.

Cheers,
Ana

**Comment by armijnhemel** [comment]
oh wow, sorry to hear that! I got all of them new. I guess the design of the device isn’t that good. I will add the warning when I have proper access to my dev machine again. Thanks!

Verstuurd vanaf mijn Eierfoon

**Comment by megfault** [comment]
I opened a PR with the warning.

Do not worry, we are all safe and sound.

**Comment by armijnhemel** [comment]
I merged the warning, closing. Thanks for the report!
